apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: s3-mounter
  name: s3-mounter
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: 
      app: s3-mounter
  template:
    metadata:
      labels:
        app: s3-mounter
    spec:
      {{ if .Values.serviceAccount.create }}
      serviceAccountName: s3-mounter
      {{- else -}}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
      - name: mounter 
        image: otomato/goofys        
        command:
          {{- range .Values.commandOption }}
          - {{ . | quote }}
          {{- end }} 
        securityContext:
          privileged: true
        volumeMounts:
        - name: mntdatas3
          mountPath: {{ .Values.mountPath }}:shared
        env:
          - name: S3_BUCKET
            value: {{ .Values.bucketName }}
          - name: MOUNT_PATH
            value: {{ .Values.mountPath }}
      volumes:
      - name: mntdatas3
        hostPath:
          path: {{ .Values.hostPath }}
